# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_search.ipynb.

# %% auto #0
__all__ = ['graph_stats']

# %% ../nbs/02_search.ipynb #code
from fastcore.all import patch
from fastlite import Database
from litesearch.core import rrf_all, sql_in

@patch
def graph_search(self:Database, q:str, emb:bytes, store:str='store', prefix:str=None,
                 limit:int=10, seedk:int=8, graph_w:float=1.0):
    "Hybrid seed, walk one relation hop to neighbour entities, pull their chunks, RRF-fuse. LLM-built typed graph."
    g = self.get_graph(store, prefix)
    base = self.search(q, emb, columns=['id','node_id'], limit=50, table_name=store) or []
    seeds = [h['id'] for h in base[:seedk]]
    if not seeds: return base[:limit]
    sent = {m['entity_id'] for m in g.mentions(select='entity_id', where=sql_in('chunk_id', seeds))}
    nbr = {e['dst'] for e in g.edges(select='dst', where=sql_in('src', list(sent)))} if sent else set()
    if not nbr: return base[:limit]
    leg_ids = list(dict.fromkeys(m['chunk_id'] for m in g.mentions(select='chunk_id', where=sql_in('entity_id', list(nbr)))))
    node = {r['id']:r['node_id'] for r in self.t[store](select='id, node_id', where=sql_in('id', leg_ids))} if leg_ids else {}
    return rrf_all([base, [dict(id=i, node_id=node.get(i)) for i in leg_ids]], k=60, limit=limit, id_key='id', weights=[1.0, graph_w])

def graph_stats(db, store='store', prefix=None):
    "Row counts and the highest-degree entities of a built graph."
    g = db.get_graph(store, prefix)
    deg = {}
    for e in g.edges(select='src, dst'):
        deg[e['src']] = deg.get(e['src'],0)+1; deg[e['dst']] = deg.get(e['dst'],0)+1
    top = sorted(deg.items(), key=lambda kv: -kv[1])[:10]
    name = {r['id']:r['content'] for r in g.entities(select='id, content')}
    return dict(entities=g.entities.count, mentions=g.mentions.count, edges=g.edges.count,
                top_degree=[dict(entity=name.get(i,i), degree=d) for i,d in top])
